config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  root "prints#index"
  resources :prints, only: [:index, :show]
  resources :adminprints, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :prints do
    resources :comments, only: :create
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :print
end

app/models/print.rb
class Print < ApplicationRecord
  mount_uploader :poster, PosterUploader
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/adminprints_controller.rb
class AdminprintsController < ApplicationController
  before_action :authenticate_admin!
  
  def create
    @print = Print.create(print_params)
    redirect_to adminprints_path
  end

  def index
    @prints = Print.all
  end

  def show
    @print = Print.find(params[:id])
  end
  

  def new
    @print = Print.new
  end

  def destroy
    @print = Print.find(params[:id])
    @print.destroy
    redirect_to adminprints_path
  end

  def edit
    @print = Print.find(params[:id])
  end

  def update
    @print = Print.find(params[:id])
    @print.update_attributes(print_params)
    redirect_to adminprints_path
  end


  private

  def print_params
    params.require(:print).permit(:poster, :venue, :location, :date, :artist)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authorize_admin
    redirect_to :back, status: 401 unless current_user.authorize_admin
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @print = Print.find(params[:print_id])
    @print.comments.create(comment_params.merge(user: current_user))
    redirect_to print_path(@print)
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController

  def index
    @prints = Print.all
  end
  
  def show
    @print = Print.find(params[:id])
    @comment = Comment.new
  end

  private

  def print_params
    params.require(:print).permit(:poster, :venue, :location, :date, :artist)
  end

end

app/helpers/adminprints_helper.rb
module AdminprintsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prints_helper.rb
module PrintsHelper
end

app/views/adminprints/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add New Print</h1>
  <%= simple_form_for @print, url: adminprint_path do |f| %>
    <%= f.input :venue %>
    <%= f.input :location %>
    <%= f.input :artist %>
    <%= f.input :date, type: "datetime-local"  %>
    <br />
    <%= f.input :poster %>
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/adminprints/index.html.erb
<table class="table">

<% @prints.each do |print| %>
  <tr>
    <td>
      <%= image_tag print.poster, class: 'img-thumbnail' %>
    </td>
    <td>
      <%= print.venue %>
    </td>
    <td>
      <%= print.location %>
    </td>
    <td>
      <%= print.date %>
    </td>
    <td>
      <%= print.artist %>
    </td>
    <td>
      <h1><%= link_to print.poster, adminprint_path(print), class: "btn btn-secondary" %></h1><br />
    </td>
  </tr>

<% end %>
</table>

<pre>
  <!-- <%= @prints.to_yaml %> -->
</pre>

app/views/adminprints/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add New Print</h1>
  <%= simple_form_for @print, url: adminprints_path do |f| %>
    <%= f.input :venue %>
    <%= f.input :location %>
    <%= f.input :artist %>
    <%= f.input :date, type: "datetime-local"  %>
    <br />
    <%= f.input :poster %>
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/adminprints/show.html.erb
<div class="container">
<br />
  <div class="row">
    <div class="col-fluid">
      <%= image_tag @print.poster, class: 'img-fluid' %>
    </div>
    <div class="col"><br /><br />
      <p>Location: <br /> <%= @print.location %></p>
      <p>Venue: <br /><%= @print.venue %></p>
      <p>Date: <br /> <%= @print.date %></p>
      <p>Artist: <br /> <%= @print.artist %></p>
      <div class="float-right">
        <%= link_to 'Edit', edit_adminprint_path(@print), class: 'btn btn-secondary' %>
        <%= link_to 'Destroy', adminprint_path(@print), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" />
  </head>

  <body>
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-brand">
    <%= link_to image_tag("pslogo.png"), root_path, class: "img-responsive" %>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%=link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%=link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <!--
    <form class="form-inline">
      <input class="form-control" type="text" placeholder="Search for Prints...">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    -->
  </div>
</nav>


<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/prints/index.html.erb
<br />
<div class="container">
 
  <div class="card-columns">

    <% @prints.each do |print| %>

    <div class="card-responsive hovereffect">
      <%= image_tag print.poster, class: 'img-fluid' %>
      <div class="overlay">
        <div class="card-block">
          <%= link_to 'Print Details', print_path(print), class: 'btn btn-secondary' %>
          <br /><br />
          <p class="card-title">Venue: <%= print.venue %></p>
          <p class="text">Location: <%= print.location %></p>
          <p class="text">Artist: <%= print.artist %></p>
          <p class="text">Date: <%= print.date %></p>
        </div>
      </div>
      <br />
    </div>
    

    <% end %>
  </div>
</div>

app/views/prints/show.html.erb
<div class="container">
<br />
  <div class="row">
    <div class="col-fluid">
      <%= image_tag @print.poster, class: 'img-fluid' %>
    </div>
    <div class="col"><br /><br />
      <small>Location: <br /></small>
        <p><%= @print.location %></p>
      <small>Venue: <br /></small>
        <p><%= @print.venue %></p>
      <small>Artist: <br /></small>
        <p><%= @print.artist %></p>  
      <small>Date: <br /></small>
        <p><%= @print.date %></p>
    </div>
  </div>
</div>
<br /><br /><br />

<br />

<div class="comments">
  <h3>Comments</h3>

  <%= simple_form_for @comment, url: print_comments_path(@print) do |f| %>
    <%= f.input :message, placeholder: 'Add a comment...' %>
    <%= f.submit "Add a Comment", class: 'btn btn-secondary' %>
  <% end %>
  <br />

  <% @print.comments.each do |comment| %>
    <div class="comments-list col-6">
      <p1><%= comment.message %></p1>
      <br />
      <p1 class="text-muted"><%= comment.user.email %></p1>
      <br />
    </div>
    <br />
  <% end %>
</div>